
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class PuzzleMapConfig : Luban.BeanBase
{
    public PuzzleMapConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MType = _buf.ReadInt();
        Task = _buf.ReadInt();
        UrlIcon = _buf.ReadString();
    }

    public static PuzzleMapConfig DeserializePuzzleMapConfig(ByteBuf _buf)
    {
        return new PuzzleMapConfig(_buf);
    }

    /// <summary>
    /// key值
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int MType;
    /// <summary>
    /// 关数
    /// </summary>
    public readonly int Task;
    /// <summary>
    /// 组件
    /// </summary>
    public readonly string UrlIcon;
   
    public const int __ID__ = 1740836096;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "mType:" + MType + ","
        + "task:" + Task + ","
        + "urlIcon:" + UrlIcon + ","
        + "}";
    }
}

}

