
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public TbEffectConfig TbEffectConfig {get; }
    public TbGMConfig TbGMConfig {get; }
    public TbPuzzleConfig TbPuzzleConfig {get; }
    public TbSoundConfig TbSoundConfig {get; }
    public TbTipTextConfig TbTipTextConfig {get; }
    public TbCfg_Language TbCfgLanguage {get; }
    public TbScript_Language TbScriptLanguage {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbEffectConfig = new TbEffectConfig(loader("tbeffectconfig"));
        TbGMConfig = new TbGMConfig(loader("tbgmconfig"));
        TbPuzzleConfig = new TbPuzzleConfig(loader("tbpuzzleconfig"));
        TbSoundConfig = new TbSoundConfig(loader("tbsoundconfig"));
        TbTipTextConfig = new TbTipTextConfig(loader("tbtiptextconfig"));
        TbCfgLanguage = new TbCfg_Language(loader("tbcfg_language"));
        TbScriptLanguage = new TbScript_Language(loader("tbscript_language"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbEffectConfig.ResolveRef(this);
        TbGMConfig.ResolveRef(this);
        TbPuzzleConfig.ResolveRef(this);
        TbSoundConfig.ResolveRef(this);
        TbTipTextConfig.ResolveRef(this);
        TbCfgLanguage.ResolveRef(this);
        TbScriptLanguage.ResolveRef(this);
    }
}

}
