
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbPuzzleMapConfig
{
    private readonly System.Collections.Generic.Dictionary<int, PuzzleMapConfig> _dataMap;
    private readonly System.Collections.Generic.List<PuzzleMapConfig> _dataList;
    
    public TbPuzzleMapConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, PuzzleMapConfig>();
        _dataList = new System.Collections.Generic.List<PuzzleMapConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            PuzzleMapConfig _v;
            _v = PuzzleMapConfig.DeserializePuzzleMapConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, PuzzleMapConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<PuzzleMapConfig> DataList => _dataList;

    public PuzzleMapConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PuzzleMapConfig Get(int key) => _dataMap[key];
    public PuzzleMapConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

